# -*- coding: utf-8 -*-
"""air-quality-and-pollution-assessment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0cHMaU3_lVP0wxLQw28bFwy2GlhSu28
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import joblib

# Load scaler dan label encoder
scaler = joblib.load('scaler.pkl')
label_encoder = joblib.load('label_encoder.pkl')

# Load model TFLite
interpreter = tf.lite.Interpreter(model_path="air-quality-and-pollution-assessment.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Judul Aplikasi
st.title("Air Quality and Pollution Assessment")
st.write("Masukkan informasi lingkungan untuk mendapatkan informasi kondisi udara.")

Temperature = st.number_input("Suhu (°C)", min_value=0.0, max_value=50.0, value=25.0)
Humidity = st.number_input("Kelembapan (%)", min_value=0.0, max_value=100.0, value=60.0)
PM25 = st.number_input("PM2.5 (µg/m³)", min_value=0.0, max_value=100.0, value=10.0)
PM10 = st.number_input("PM10 (µg/m³)", min_value=0.0, max_value=100.0, value=10.0)
NO2 = st.number_input("NO2 (ppb)", min_value=0.0, max_value=100.0, value=20.0)
SO2 = st.number_input("SO2 (ppb)", min_value=0.0, max_value=100.0, value=5.0)
CO = st.number_input("CO (ppm)", min_value=0.0, max_value=10.0, value=1.0)
Proximity_to_Industrial_Areas = st.number_input("Proximity to Industrial Areas (km)", min_value=0.0, max_value=20.0, value=5.0)
Population_Density = st.number_input("Population Density (per km²)", min_value=0, max_value=1000, value=500)

if st.button("Informasi Kualitas Udara"):
    # Preprocess input
    input_data = np.array([[Temperature,Humidity,PM25,PM10,NO2,SO2,CO,Proximity_to_Industrial_Areas,Population_Density]])
    input_scaled = scaler.transform(input_data).astype(np.float32)

    # Predict the air quality
    predicted_class = model.predict(input_scaled)
    predicted_air = le.inverse_transform(predicted_class)[0]

    st.success(f"Kualitas Udara: **{predicted_air.upper()}**")
